import { Gliff } from "gliff";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { displayFamily, monoFamily, textFamily } from "#utils/font";
import "./globals.css";

export const metadata: Metadata = {
	title: "Ritik's Lab",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: TRootProps) {
	return (
		<html lang="en" className={`${displayFamily.variable} ${textFamily.variable} ${monoFamily.variable} antialiased`} suppressHydrationWarning>
			<head>
				<meta name="view-transition" content="same-origin" />
				<Gliff next />
			</head>
			<body>{children}</body>
		</html>
	);
}

type TRootProps = {
	children: ReactNode;
};
